### ISSUE TITLE
Deploy mediawiki

### ISSUE THREAD

**Issue by marcondag** [debtsyndicate/parent#5]
In gitlab by @marcondag on Feb 19, 2018, 14:34

## Acceptance Criteria

- [ ] Mediawiki is deployed at wiki.debtcollective.org
- [ ] Terraform created to deploy in ~ECS~ EC2

## Resources

https://hub.docker.com/_/mediawiki/

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 19, 2018, 17:18

changed the description

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 19, 2018, 17:21

added ~3522318 label

**Comment by orlando** [comment]
Closed by https://github.com/debtsyndicate/ds-terraform/pull/2
