### ISSUE TITLE
`seeds` vs `migrations`

### ISSUE THREAD

**Issue by marcondag** [debtsyndicate/parent#50]
In gitlab by @shoshber on Feb 21, 2018, 10:49

A recent deployment to staging failed due to confusion regarding our philosophy on seed vs migration files. (https://gitlab.com/debtcollective/debtcollective/merge_requests/174/diffs).

## Acceptance criteria

* [ ] update `README` with instructions for developers

from https://gitlab.com/debtcollective/debtcollective/issues/313

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 10:49

mentioned in issue debtcollective#313

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 10:50

assigned to @marcondag

**Comment by orlando** [comment]
We can use migrations to modify or include data, since `seeds` are only run once, and by now that the project is in production, is difficult to do these things with seeds without having problems with the current dataset.

_so, is fine to modify data in migrations_
