### ISSUE TITLE
Rewrite disputes ACL handler to be tested and clearer

### ISSUE THREAD

**Issue by marcondag** [debtsyndicate/parent#58]
In gitlab by @shoshber on Feb 21, 2018, 11:32

The ACL handler currently has no testing and is a nightmare to debug/work with. It also has no documentation whatsoever. This is issue is to write tests for it then refactor it to be clearer and easier to understand, along with documenting the process of editing ACL routes. Part of this will involve resolving a TODO in `lib/ACL/acl_helpers.js`:

>   ```javascript
    18  const fixedTests = test.map(check =>  
    19    // TODO: consider Promise.each() for sequence checks  
    20    check(acl, req),  
    21 );  

## Acceptance criteria

In such order:

- [ ] ACL handler is tested to 90% coverage
- [ ] ACL handler is refactored to be clear and passes all tests
- [ ] Unclear parts are documented
- [ ] route protection/guarding is clear and easy to work with
- [ ] All the stuff unrelated to disputes can be removed!?
- [ ] TODO is resolved (likely through the refactor)

We should not/do not want to have to update the `ACL` configuration files.

https://gitlab.com/debtcollective/debtcollective/issues/317

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 11:33

changed the description

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 11:33

added ~3522123 label

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 11:34

mentioned in issue debtcollective#317

**Comment by orlando** [comment]
This is invalid, @marcondag implemented a cleaner way to do it in the new Dispute Tools app
