### ISSUE TITLE
Deploy Dispute tool to debtcollective.org

### ISSUE THREAD

**Issue by orlando** [debtsyndicate/parent#87]
Deploy the new version of the Dispute tools that only contains that to tools.debtsyndicate.org

- [ ] New Dispute only version should be deployed to tools.debtsyndicate.org
- [ ] Smoke test to make sure the main flow (create a Dispute) works correctly

**Comment by marcondag** [comment]
Note that this is not the debtsyndicate/dispute-tools that is being deployed but the one located at https://gitlab.com/debtcollective/debtcollective.

**Comment by orlando** [comment]
Last version deployed to production
